name       : iftop
version    : 1.0_pre4
release    : 5
source     :
    - http://www.ex-parrot.com/pdw/iftop/download/iftop-1.0pre4.tar.gz : f733eeea371a7577f8fe353d86dd88d16f5b2a2e702bd96f5ffb2c197d9b4f97
homepage   : http://www.ex-parrot.com/pdw/iftop
license    : GPL-2.0
component  : system.utils
summary    : View network usage in a format similar to 'top'
description: |
    iftop listens to network traffic on interfaces and displays a table of bandwidth usage by hosts similar to how top(1) displays CPU usage.
builddeps  :
    - libpcap-devel
rundeps    :
    - libpcap
environment: |
    export CFLAGS="${CFLAGS} -fcommon"
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
